### ISSUE TITLE
Some early jun are not reviewed

### ISSUE THREAD

**Issue by pliuphys** [Equim-chan/akochan-reviewer#15]
I've seen a few times when for the first few jun when Akochan thinks an honor tile should be discarded, no analysis is given even if the player didn't discard said tile. 

Here's an example from a Suphx game
akochan-reviewer.exe --no-open -n 0.4 --pt 75,30,0,-105 "https://tenhou.net/4/?log=2019031218gm-0029-0000-d756d03c&tw=1"
![キャプチャ](https://user-images.githubusercontent.com/25420481/114949624-60320e00-9e1f-11eb-96e8-4e959a5f94d9.JPG)

**Comment by Equim-chan** [comment]
This behavior is intended.

Akochan runs in rule-based mode under certain conditions, like if the game is at an early stage, and our shanten number is high, and we are not folding currently. In such mode, akochan will choose the most efficient tile to discard and doesn't bother calculating any deal-in rate or EV, so only one choice without any EV info will be produced. It is not that akochan can't run with normal mode instead of rule-based mode under such circumstance, but the cost will be much higher making the review slower.

If the reviewer sees akochan running in such mode, it is not sure how to compare the discards akochan and the player made due to the lack of information, so it simply gives up doing that, leaving it as an accepted entry even if the choices are different.

**Comment by pliuphys** [comment]
So if we want that information using normal node we'll have to modify akochan? I'm confused by early round choices very often so it would be great if we have a switch.

**Comment by Equim-chan** [comment]
Yes you'll need to modify akochan.

In `ai_src/selector.cpp:Selector::set_selector`

```diff
-const bool rule_base_flag = tehai_analyzer.rule_base_decision(my_pid);
+const bool rule_base_flag = false;
```

**Comment by pliuphys** [comment]
Thanks! Since I'll not be able to test in the very near term let me close the issue.
