### ISSUE TITLE
(Partially) Re-enable akochan for Mahjong Soul

### ISSUE THREAD

**Issue by SAPikachu** [Equim-chan/akochan-reviewer#44]
I am maintainer of [雀魂牌譜屋](https://amae-koromo.sapk.ch/). Since my server caches log data for recent matches (usually for 1 ~ 2 days), I think akochan can use these data to allow reviewing recent matches. What do you think? If you like this idea, I can message you an HTTP endpoint for getting log data. :)

**Comment by Equim-chan** [comment]
Hi, thank you for your hard efforts running the useful site.

I think my [tensoul](https://github.com/Equim-chan/tensoul) isn't broken yet aside from some possibly needed updates; it just demands a good reliable host for it to be deployed so that all logs will be accessible again. But I have been busy working my new AI engine for the recent months, so I've put this on hold.

**Comment by SAPikachu** [comment]
I see, cheers!
